USE babblefish
GO

DECLARE @MyYear AS DATETIME
SET @MyYear = '1/1/2015'

DECLARE @MyQtr AS INT
SET @MyQtr = 1

DECLARE @YearCount AS INT
SET @YearCount = 2015

WHILE @YearCount <= 2020
BEGIN
	WHILE @MyQtr < 5
		BEGIN

			SELECT
				DATEPART(YEAR, a.ATTACHDATE)
			   ,DATEPART(QUARTER, a.ATTACHDATE)
				--,a.FILENAME
			   ,COUNT(*)
			FROM ATTACHMENT a
			WHERE DATEPART(YEAR, a.ATTACHDATE) = DATEPART(YEAR, '1/1/' + CONVERT(VARCHAR, @YearCount))
			AND DATEPART(QUARTER, a.ATTACHDATE) = @MyQtr
			GROUP BY DATEPART(YEAR, a.ATTACHDATE)
					,DATEPART(QUARTER, a.ATTACHDATE)

			--,a.FILENAME
			SET @MyQtr = @MyQtr + 1
		END
		SET @YearCount = @YearCount + 1
		SET @MyQtr = 1
end
--DECLARE @audit_num INT
--SET @audit_num = NEXT VALUE FOR audit_zipfiles_seq

--SELECT
--	--DATEPART(YEAR, a.ATTACHDATE)
--   --,DATEPART(QUARTER, a.ATTACHDATE)
--   @audit_num
--   ,a.FILENAME
--FROM ATTACHMENT a
--WHERE a.ATTACHDATE >= '1/1/2020'
--AND a.FILENAME LIKE ('Mail Merge%')
--GROUP BY DATEPART(YEAR, a.ATTACHDATE)
--		,DATEPART(QUARTER, a.ATTACHDATE)
--		,a.FILENAME

