USE [babblefish]
GO

/****** Object:  Table [dbo].[PRODUCT]    Script Date: 3/3/2020 5:48:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCT](
	[PRODUCTID] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[ACTUALID] [nvarchar](255) NULL,
	[FAMILY] [nvarchar](255) NULL,
	[PRICE] [float] NULL,
	[CREATEDATE] [datetime] NULL,
	[CREATEUSER] [nvarchar](255) NULL,
	[MODIFYDATE] [datetime] NULL,
	[MODIFYUSER] [nvarchar](255) NULL,
	[PRODUCTGROUP] [nvarchar](255) NULL,
	[STATUS] [nvarchar](255) NULL,
	[UNIT] [nvarchar](255) NULL,
	[STOCKVOLUME] [nvarchar](255) NULL,
	[STOCKWEIGHT] [nvarchar](255) NULL,
	[STOCKITEM] [nvarchar](255) NULL,
	[PROGRAM] [datetime] NULL,
	[SUPPLIER] [nvarchar](255) NULL,
	[VENDOR] [datetime] NULL,
	[SITEID] [nvarchar](255) NULL,
	[WAREHOUSELOCATION] [nvarchar](255) NULL,
	[COMMISSIONABLE] [nvarchar](255) NULL,
	[TAXABLE] [nvarchar](255) NULL,
	[ACCOUNTINGPERIOD] [nvarchar](255) NULL,
	[GLACCOUNTNUMBER] [nvarchar](255) NULL,
	[GLSUBACCOUNTNUMBER] [nvarchar](255) NULL,
	[DATAOWNER] [nvarchar](255) NULL,
	[TYPE] [nvarchar](255) NULL,
	[FIXEDCOST] [float] NULL,
	[PRODUCTWEBNAME] [nvarchar](255) NULL,
	[PRODUCTDESCRIPTION] [nvarchar](255) NULL,
	[PRODUCTPICTUREPATH1] [nvarchar](255) NULL,
	[PRODUCTPICTUREPATH2] [nvarchar](255) NULL,
	[ACTIVATEONWEB] [nvarchar](255) NULL,
	[PRODUCTPDF] [nvarchar](255) NULL,
	[PRODUCTPARTNUMBER] [nvarchar](255) NULL,
	[PRODUCTPSI] [nvarchar](255) NULL,
	[PRODUCTDIMENSIONS] [nvarchar](255) NULL,
	[PRODUCTCOMMENT] [nvarchar](255) NULL,
	[PRODUCTCHARGINGRATE] [nvarchar](255) NULL,
	[PRODUCTNEW] [nvarchar](255) NULL,
	[PRODUCTUSED] [nvarchar](255) NULL,
	[PRODUCTMARKETINGMESSAGE] [nvarchar](255) NULL,
	[PRODUCTPICTURELABEL1] [nvarchar](255) NULL,
	[PRODUCTPICTURELABEL2] [nvarchar](255) NULL,
	[PRODUCTQUOTEABLE] [nvarchar](255) NULL,
	[PRODUCTORDERABLE] [nvarchar](255) NULL,
	[IMPORTSOURCE] [nvarchar](255) NULL,
	[GLOBALSYNCID] [nvarchar](255) NULL,
	[APPID] [nvarchar](255) NULL,
	[TICK] [nvarchar](255) NULL,
	[COMMODITYGROUPID] [nvarchar](255) NULL,
	[ACTIVEFLAG] [nvarchar](255) NULL,
	[SELLINGALLOWEDFLAG] [nvarchar](255) NULL,
	[UNITOFMEASUREID] [nvarchar](255) NULL,
	[SELLINGUOMID] [nvarchar](255) NULL,
	[SELLINGUOMNUMBER] [nvarchar](255) NULL,
	[CLASSIFICATION] [nvarchar](255) NULL,
	[COMMODITYTYPE] [nvarchar](255) NULL,
	[CREATESOURCE] [nvarchar](255) NULL,
	[ERPEXTID] [nvarchar](255) NULL,
	[ERPLOGICALID] [nvarchar](255) NULL,
	[ERPACCOUNTINGENTITYID] [nvarchar](255) NULL,
	[ERPCONFIGUREDITEM] [nvarchar](255) NULL,
	[ERPLEADTIME] [nvarchar](255) NULL,
	[ERPUPCID] [nvarchar](255) NULL,
	[ERPSERVICEPRODUCT] [nvarchar](255) NULL,
	[ERPSTATUSDATE] [datetime] NULL,
	[ERPLOTCONTROLLED] [nvarchar](255) NULL,
	[ERPSERIALCONTROLLED] [nvarchar](255) NULL,
	[ERPSHELFLIFE] [nvarchar](255) NULL,
	[ERPSTORAGEUOM] [nvarchar](255) NULL,
	[ERPUNIQUEID] [nvarchar](255) NULL,
	[ERPLASTREFRESH] [datetime] NULL,
	[ERPCOSTMETHOD] [nvarchar](255) NULL,
	[ERPCOST] [nvarchar](255) NULL,
	[ERPPERQUANTITY] [nvarchar](255) NULL,
	[ERPPERQUANTITYUOM] [nvarchar](255) NULL,
	[ERPVARIATIONID] [nvarchar](255) NULL,
	[ERPSTATUS] [nvarchar](255) NULL,
	[CURRENCYCODE] [nvarchar](255) NULL,
	[INTEGRATIONCONFIGGROUPID] [nvarchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


