USE babblefish
GO

/****** Object:  Table [sysdba].[HISTORY]    Script Date: 3/4/2020 3:59:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HISTORY] (
	[HISTORYID] NVARCHAR(255) NOT NULL
   ,[ACTIVITYID] NVARCHAR(255) NULL
   ,[TYPE] [INT] NULL
   ,[ACCOUNTID] NVARCHAR(255) NULL
   ,[CONTACTID] NVARCHAR(255) NULL
   ,[OPPORTUNITYID] NVARCHAR(255) NULL
   ,[ACCOUNTNAME] [VARCHAR](128) NULL
   ,[CONTACTNAME] [VARCHAR](128) NULL
   ,[OPPORTUNITYNAME] [VARCHAR](64) NULL
   ,[PRIORITY] [VARCHAR](64) NULL
   ,[CATEGORY] [VARCHAR](64) NULL
   ,[STARTDATE] [DATETIME] NULL
   ,[DURATION] [INT] NULL
   ,[DESCRIPTION] [VARCHAR](255) NULL
   ,[PROCESSID] NVARCHAR(255) NULL
   ,[PROCESSNODE] [VARCHAR](16) NULL
   ,[TIMELESS] NVARCHAR(255) NULL
   ,[RECURRING] NVARCHAR(255) NULL
   ,[ACTIVITYBASEDON] NVARCHAR(255) NULL
   ,[USERID] NVARCHAR(255) NULL
   ,[USERNAME] [VARCHAR](64) NULL
   ,[ORIGINALDATE] [DATETIME] NULL
   ,[RESULT] [VARCHAR](64) NULL
   ,[RESULTCODE] [VARCHAR](8) NULL
   ,[CREATEDATE] [DATETIME] NULL
   ,[CREATEUSER] NVARCHAR(255) NULL
   ,[MODIFYDATE] [DATETIME] NULL
   ,[MODIFYUSER] NVARCHAR(255) NULL
   ,[COMPLETEDDATE] [DATETIME] NULL
   ,[COMPLETEDUSER] NVARCHAR(255) NULL
   ,[NOTES] [VARCHAR](255) NULL
   ,[LONGNOTES] TEXT NULL
   ,[ATTACHMENT] NVARCHAR(255) NULL
   ,[USERDEF1] [VARCHAR](255) NULL
   ,[USERDEF2] [VARCHAR](255) NULL
   ,[USERDEF3] [VARCHAR](255) NULL
   ,[TICKETID] [char](12) NULL
   ,[TICKETNUMBER] [VARCHAR](64) NULL
   ,[LEADNAME] [VARCHAR](64) NULL
   ,[LEADID] [char](12) NULL
   ,[ATTACHMENTCOUNT] [INT] NULL
   ,[LOCATION] [VARCHAR](255) NULL
   ,[CREATESOURCE] [VARCHAR](64) NULL
   ,[APPID] [char](12) NULL
   ,[GLOBALSYNCID] [VARCHAR](36) NULL
   ,[TICK] [INT] NULL
)
SET ANSI_PADDING OFF
GO

