USE [babblefish]
GO

/****** Object:  Table [dbo].[ATTACHMENT_TEMPLATE_IMPORT]    Script Date: 3/10/2020 7:28:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE ATTACHMENT_CSV

CREATE TABLE [dbo].ATTACHMENT_CSV (
	[ATTACHID] [NVARCHAR](255) NOT NULL
   ,[EXTERNAL ID] [NVARCHAR](255) NULL
   ,[INTERNAL ID] [FLOAT] NULL
   ,[CASENUMBERREF] [VARCHAR](1) NOT NULL
   ,[TRANSACTIONHANDLE] [VARCHAR](1) NOT NULL
   ,[TITLE] [VARCHAR](128) NULL
   ,[TYPEREF] [VARCHAR](1) NOT NULL
   ,[DIRECTIONREF] [VARCHAR](1) NOT NULL
   ,[MEMO] [VARCHAR](128) NULL
   ,[FILENAME] [NVARCHAR](256) UNIQUE NOT NULL
   ,[ATTACHDATE] DATE NULL
   ,ATTACHTIME VARCHAR(16) NULL
   ,[RUN_ID] INT NOT NULL
   ,SOURCEFILENAME [NVARCHAR](255) NOT NULL
) ON [PRIMARY]
GO


