USE babblefish
GO

/****** Object:  Table [sysdba].[ATTACHMENT]    Script Date: 3/4/2020 8:06:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ATTACHMENT] (
	[ATTACHID] NVARCHAR(255) NOT NULL
   ,[ATTACHDATE] [DATETIME] NULL
   ,[ACCOUNTID] NVARCHAR(255) NULL
   ,[CONTACTID] NVARCHAR(255) NULL
   ,[OPPORTUNITYID] NVARCHAR(255) NULL
   ,[DESCRIPTION] [VARCHAR](128) NULL
   ,[DATATYPE] NVARCHAR(255) NULL
   ,[FILESIZE] [INT] NULL
   ,[FILENAME] [VARCHAR](255) NULL
   ,[USERID] NVARCHAR(255) NULL
   ,[DATA] NVARCHAR(255) NULL
   ,[CONTRACTID] NVARCHAR(255) NULL
   ,[DEFECTID] NVARCHAR(255) NULL
   ,[DOCUMENTTYPE] [VARCHAR](80) NULL
   ,[PROCEDUREID] NVARCHAR(255) NULL
   ,[PRODUCTID] NVARCHAR(255) NULL
   ,[RMAID] NVARCHAR(255) NULL
   ,[TICKETID] NVARCHAR(255) NULL
   ,[HISTORYID] [char](12) NULL
   ,[MODIFYDATE] [DATETIME] NULL
   ,[MODIFYUSER] [char](12) NULL
   ,[CREATEDATE] [DATETIME] NULL
   ,[CREATEUSER] [char](12) NULL
   ,[LEADID] [char](12) NULL
   ,[ACTIVITYID] [VARCHAR](12) NULL
   ,[SALESORDERID] [char](12) NULL
   ,[CREATESOURCE] [VARCHAR](64) NULL
   ,[QUOTEID] [char](12) NULL
) ON [PRIMARY]
GO
