SELECT
	sae.BWCUSTOMERID
FROM SLX_Account_ext sae
WHERE ISNUMERIC(sae.BWCUSTOMERID) > 0
GROUP BY sae.BWCUSTOMERID
HAVING COUNT(*) = 1
ORDER BY sae.BWCUSTOMERID

SELECT ac.UDF_BWID FROM AR_Customer ac
WHERE ac.UDF_BWID = '110042'

SELECT sae.BWCUSTOMERID FROM SLX_Account_ext sae
--WHERE sae.BWCUSTOMERID = '110042'
GROUP BY sae.BWCUSTOMERID
HAVING COUNT(sae.BWCUSTOMERID) = 1
