/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CustomerName]
      ,[CreditLimit]
      ,[EmailAddress]
      ,[UDF_BWID]
      ,[Status]
      ,[FaxNo]
      ,[INDIVIDUAL]
      ,[TelephoneNo]
      ,[PRIMARY_SUBSIDARY]
      ,[TaxSchedule]
      ,[TermsCode]
      ,[URLAddress]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[AddressLine3]
      ,[City]
      ,[CountryCode]
      ,[ZipCode]
      ,[Internal ID]
      ,[ID]
      ,[External ID]
      ,[EMAIL]
      ,[Phone]
      ,[Web Address]
  FROM [master].[dbo].[Q2DATA]