/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CustomerName]
      ,[CreditLimit]
      ,[ARDivisionNo]
      ,[EmailAddress]
      ,[UDF_BWID]
      ,[Status]
      ,[FaxNo]
      ,[INDIVIDUAL]
      ,[TelephoneNo]
      ,[PRIMARY_SUBSIDARY]
      ,[TaxSchedule]
      ,[TermsCode]
      ,[URLAddress]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[AddressLine3]
      ,[City]
      ,[CountryCode]
      ,[ZipCode]
      ,[ID]
      ,[pid]
  FROM [master].[dbo].[Q3DATA_CHILDREN]